services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\HybridPlatformUi\Components\App:
        arguments:
            $toolbars: ["@ezsystems.platformui.component.discoverybar"]

    EzSystems\HybridPlatformUi\Components\NavigationHub:
        arguments:
            $request: '@=service("request_stack").getMasterRequest()'
            $zones: []
            $links: []

    EzSystems\HybridPlatformUi\Components\MainContent: ~
