parameters:
    ezsystems.platformui.navigationhub.zone.class: EzSystems\HybridPlatformUi\NavigationHub\Zone
    ezsystems.platformui.navigationhub.link.route.class: EzSystems\HybridPlatformUi\NavigationHub\Link\Route
    ezsystems.platformui.navigationhub.link.subtree.class: EzSystems\HybridPlatformUi\NavigationHub\Link\Subtree

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ezsystems.platformui.navigationhub.zones.content:
        class: "%ezsystems.platformui.navigationhub.zone.class%"
        arguments:
            - "Content"
            - "content"
        tags:
            - name: ezplatform.ui.zone
              priority: 100

    ezsystems.platformui.navigationhub.zones.page:
        class: "%ezsystems.platformui.navigationhub.zone.class%"
        arguments:
            - "Page"
            - "page"
        tags:
            - name: ezplatform.ui.zone
              priority: 200

    ezsystems.platformui.navigationhub.zones.performances:
        class: "%ezsystems.platformui.navigationhub.zone.class%"
        arguments:
            - "Performances"
            - "performances"
        tags:
            - name: ezplatform.ui.zone
              priority: 300

    ezsystems.platformui.navigationhub.zones.admin:
        class: "%ezsystems.platformui.navigationhub.zone.class%"
        arguments:
            - "Admin Panel"
            - "admin"
        tags:
            - name: ezplatform.ui.zone
              priority: 400

    ezsystems.platformui.navigationhub.link.contentstructure:
        class: "%ezsystems.platformui.navigationhub.link.subtree.class%"
        arguments:
            - "@router"
            - "Content structure"
            - "content"
            - {locationId: 2}
        tags:
            - name: ezplatform.ui.link
              priority: 100

    ezsystems.platformui.navigationhub.link.medialibrary:
        class: "%ezsystems.platformui.navigationhub.link.subtree.class%"
        arguments:
            - "@router"
            - "Media Library"
            - "content"
            - {locationId: 43}
        tags:
            - name: ezplatform.ui.link
              priority: 200

    ezsystems.platformui.navigationhub.link.admin.dashboard:
        class: "%ezsystems.platformui.navigationhub.link.route.class%"
        arguments:
            - "@router"
            - "admin_dashboard"
            - "Dashboard"
            - "admin"
        tags:
            - name: ezplatform.ui.link
              priority: 100

    ezsystems.platformui.navigationhub.link.admin.section:
        class: "%ezsystems.platformui.navigationhub.link.route.class%"
        arguments:
            - "@router"
            - "admin_sectionlist"
            - "Sections"
            - "admin"
        calls:
            - [setRoutePrefix, ["admin_section"]]
        tags:
            - name: ezplatform.ui.link
              priority: 200

    ezsystems.platformui.navigationhub.link.admin.languages:
        class: "%ezsystems.platformui.navigationhub.link.route.class%"
        arguments:
            - "@router"
            - "admin_languagelist"
            - "Languages"
            - "admin"
        calls:
            - [setRoutePrefix, ["admin_language"]]
        tags:
            - name: ezplatform.ui.link
              priority: 300

    ezsystems.platformui.navigationhub.link.admin.content_types:
        class: "%ezsystems.platformui.navigationhub.link.route.class%"
        arguments:
            - "@router"
            - "admin_contenttypeGroupList"
            - "Content types"
            - "admin"
        calls:
            - [setRoutePrefix, ["admin_contenttype"]]
        tags:
            - name: ezplatform.ui.link
              priority: 400

    ezsystems.platformui.navigationhub.link.admin.roles:
        class: "%ezsystems.platformui.navigationhub.link.route.class%"
        arguments:
            - "@router"
            - "admin_roleList"
            - "Roles"
            - "admin"
        calls:
            - [setRoutePrefix, ["admin_role"]]
        tags:
            - name: ezplatform.ui.link
              priority: 500

    ezsystems.platformui.navigationhub.link.admin.system_info:
        class: "%ezsystems.platformui.navigationhub.link.route.class%"
        arguments:
            - "@router"
            - "admin_systeminfo"
            - "System info"
            - "admin"
        tags:
            - name: ezplatform.ui.link
              priority: 600
