services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\HybridPlatformUi\Pjax\PjaxResponseMainContentMapper:
        alias: EzSystems\HybridPlatformUi\Pjax\DomXpathPjaxResponseMainContentMapper

    EzSystems\HybridPlatformUi\Pjax\PjaxResponseMatcher:
        alias: EzSystems\HybridPlatformUi\Pjax\MarkupPjaxResponseMatcher

    EzSystems\HybridPlatformUi\Pjax\MarkupPjaxResponseMatcher: ~

    EzSystems\HybridPlatformUi\Pjax\DomXpathPjaxResponseMainContentMapper: ~
