ez_hybrid_platform_ui_dashboard:
    path: /dashboard
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Dashboard:viewDashboard
    methods: [GET]
ez_hybrid_platform_ui_dashboard_view_tab:
    path: /dashboard/view/{sectionIdentifier}/{tabIdentifier}
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Dashboard:viewTab
    methods: [GET]
ez_hybrid_platform_ui_version_draft_actions:
    path: /content/{contentId}/versions/drafts
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Version:draftActions
    methods: [POST]
ez_hybrid_platform_ui_version_archive_actions:
    path: /content/{contentId}/versions/archives
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Version:archiveActions
    methods: [POST]
ez_hybrid_platform_ui_location_actions:
    path: /content/{contentId}/locations
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Location:actions
    methods: [POST]
ez_hybrid_platform_ui_location_swap_location:
    path: /content/{contentId}/location/{locationId}/swap
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Location:swapLocation
    methods: [POST]
ez_hybrid_platform_ui_location_sort_order:
    path: /content/{contentId}/locations/{locationId}/sortorder
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Location:updateDefaultSortOrder
    methods: [POST]
ez_hybrid_platform_ui_translation_actions:
    path: /content/{contentId}/translations
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Translation:actions
    methods: [POST]
