ez_hybrid_platform_ui_dashboard:
    path: /dashboard
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Dashboard:viewDashboard
    methods: [GET]
ez_hybrid_platform_ui_version_draft_actions:
    path: /version/draft-actions/{contentId}
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Version:draftActions
    methods: [POST]
ez_hybrid_platform_ui_location_actions:
    path: /location/actions/{contentId}
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Location:actions
    methods: [POST]
