parameters:
    ezpublish.twig.extension.location.class: EzSystems\HybridPlatformUi\Templating\Twig\LocationExtension

services:
    ezpublish.twig.extension.location:
        class: "%ezpublish.twig.extension.location.class%"
        arguments:
            - "@ezpublish.api.service.inner_location"
        tags:
            - { name: twig.extension }
