system:
    admin:
        content_view:
            full:
                default:
                    template: "EzSystemsHybridPlatformUiBundle::locationview.html.twig"
                    match: true
            details_tab:
                default:
                    template: "EzSystemsHybridPlatformUiBundle:content/tabs:details.html.twig"
                    controller: "EzSystemsHybridPlatformUiBundle:ContentView:detailsTab"
                    match: true
            versions_tab:
                default:
                    template: "EzSystemsHybridPlatformUiBundle:content/tabs:versions.html.twig"
                    controller: 'EzSystems\HybridPlatformUiBundle\Controller\ContentViewController:versionsTabAction'
                    match: true
            locations_tab:
                default:
                    template: "EzSystemsHybridPlatformUiBundle:content/tabs:locations.html.twig"
                    controller: 'EzSystems\HybridPlatformUiBundle\Controller\ContentViewController:locationsTabAction'
                    match: true
            translations_tab:
                default:
                    template: "EzSystemsHybridPlatformUiBundle:content/tabs:translations.html.twig"
                    controller: 'EzSystems\HybridPlatformUiBundle\Controller\ContentViewController:translationsTabAction'
                    match: true
